# **Genomic analysis of malaria vectors in The Gambia**
Figure 4 (4a / 4b) _ Supplementary Figures S8 & S9

### **Metabolic resistance**

- In this notebook, we compute and visualise the frequencies of CNVs in known metabolic gene classes in *Anopheles arabiensis* population from the Gambia.

In [28]:
!pip install -q malariagen_data

In [29]:
!pip install -q "plotly<6" kaleido==0.2.1

In [34]:
import malariagen_data
import os
import kaleido
import plotly.express as px
import pandas as pd

In [31]:
try:
    from google.colab import drive, output
    output.enable_custom_widget_manager()
    drive.mount("drive")
    base_dir = "drive/MyDrive/Colab Data/gm-analysis"
except ImportError:
    base_dir = "../results/gm-analysis"

results_dir = os.path.join(base_dir, "Snp_Cnv_freq-results")

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

In [32]:
git_dir = "/content/drive/My Drive/Colab Data/divergent-genetic-insecticide-resistance-in-gambian-malaria-vector"
try:
  figures_dir = os.path.join(git_dir, "figures")
except NameError:
  figures_dir = "../figures"
os.makedirs(results_dir, exist_ok=True)

In [ ]:
figures_dir

In [33]:
ag3 = malariagen_data.Ag3()
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : gs://vo_agam_release_master_us_central1/
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
Results cache                         : None
Cohorts analysis                      : 20260120
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.10.0
Client location                       : South Carolina, United States (Google Cloud us-east1)
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
---
Please note that data are subject to terms of use,
for more information see the Vector Observatory website https://www.malariagen.net/vobs/
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.10.0/Ag3.html

In [ ]:
gambia_sample_query = "country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and sample_id!='VBS47740-6366STDY9854349' and unrestricted_use == True"

In [ ]:
# access metadata
df_samples_gambia = ag3.sample_metadata(sample_query=gambia_sample_query)
df_samples_gambia

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Kerewan,GM-N,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4
310,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
311,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
312,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
313,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

In [ ]:
df_samples_gambia.pivot_table(
    index=["admin1_name", "admin2_name", "year"],
    columns="taxon",
    values="sample_id",
    aggfunc="count",
    fill_value=0,
)

taxon                               arabiensis
admin1_name admin2_name       year
Basse       Basse             2019          28
            Jimara            2019          37
            Sandu             2019           8
            Tumana            2019          21
            Wuli East         2019           1
Brikama     Foni Brefet       2019           1
            Kombo Central     2019          28
Janjanbureh Lower Fuladu West 2019          51
            Niamina East      2019          10
            Niamina West      2019           8
            Upper Fuladu West 2019          12
Kanifing    Bakau             2019           6
            Jeshwang          2019          77
Kerewan     Illiasa           2019           3
            Lower Niumi       2019          13
Kuntaur     Niani             2019           4
Mansakonko  Jarra East        2019           6

### **Metabolic Resistance**

### **Cyp450_keap_gste locus CNV Freq -- Supplementary Figure S4a **

In [ ]:
################ Cyt P450 // Gste // Keap 1 metabolik CNV Freq ###########
cyp6aap_region = "2R:28,480,000-28,510,000"
cyp9k1_region = "X:15,240,000-15,250,000"
#cyp6mz_region = "3R:6,924,000-6,980,000" # This is displaying 3 more genes i dont wont so let reduce the range of 6mz genes !!!
cyp6mz_region = "3R:6,970,000-6,980,000"  # THe first gene of interest start with at 6971582 and the 2nd end at 6975563
keap1_region = "2R:40,926,195-40,945,169"
gste1_region = "3R:28,598,871-28,599,816"
gste2_region = "3R:28,597,652-28,598,640"
cyp_regions = [keap1_region, cyp6aap_region, cyp6mz_region, cyp9k1_region, gste1_region, gste2_region]

In [ ]:
df_cyp_keap_gste_cnv_freq = ag3.gene_cnv_frequencies(
    sample_query="country == 'Gambia, The' and taxon == 'arabiensis' and sample_id!='VBS47740-6366STDY9854349'and release == '3.5'",
    cohorts="admin2_year",
    region=cyp_regions,
    sample_sets="3.5",  # needed because CNV data not released for 3.1
   # drop_invariant=False,
)
df_cyp_keap_gste_cnv_freq

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/1 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/11 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/3 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/1 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/1 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/48 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/1 [00:00<?, ?it/s]

                              gene_strand  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                -
AGAP002862 CYP6AA1   amp                -
AGAP013128 CYP6AA2   amp                -
AGAP002867 CYP6P4    amp                -
AGAP002868 CYP6P1    amp                -
AGAP008217 CYP6Z3    amp                -
AGAP008218 CYP6Z2    amp                -
                     del                -
AGAP000818 CYP9K1    amp                -
AGAP009195 GSTE1     amp                -
AGAP009194 GSTE2     amp                -

                                                                gene_description  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del       kelch-like protein 19 [Source:VB Community Ann...
AGAP002862 CYP6AA1   amp        cytochrome P450 [Source:VB Community Annotation]
AGAP013128 CYP6AA2   amp        cytochrome P450 [Source:VB Community Annotation]
AGAP002867 CYP6P4    amp        cytochrome P450 [Source:VB Community Annotation]
AGAP002868 CYP6P1    amp        cytochrome P450 [Source:VB Community Annotation]
AGAP008217 CYP6Z3    amp        cytochrome P450 [Source:VB Community Annotation]
AGAP008218 CYP6Z2    amp        cytochrome P450 [Source:VB Community Annotation]
                     del        cytochrome P450 [Source:VB Community Annotation]
AGAP000818 CYP9K1    amp        cytochrome P450 [Source:VB Community Annotation]
AGAP009195 GSTE1     amp       glutathione S-transferase epsilon class 1 [Sou...
AGAP009194 GSTE2     amp       glutathione S-transferase epsilon class 2 [Sou...

                              contig     start       end  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del          2R  40926195  40945169
AGAP002862 CYP6AA1   amp          2R  28480576  28482637
AGAP013128 CYP6AA2   amp          2R  28483301  28484921
AGAP002867 CYP6P4    amp          2R  28497087  28498674
AGAP002868 CYP6P1    amp          2R  28499251  28500900
AGAP008217 CYP6Z3    amp          3R   6971582   6973413
AGAP008218 CYP6Z2    amp          3R   6973779   6975563
                     del          3R   6973779   6975563
AGAP000818 CYP9K1    amp           X  15240572  15242864
AGAP009195 GSTE1     amp          3R  28598871  28599816
AGAP009194 GSTE2     amp          3R  28597652  28598640

                               frq_GM-M_Lower-Fuladu-West_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                                   0.421053
AGAP002862 CYP6AA1   amp                                   0.210526
AGAP013128 CYP6AA2   amp                                   0.210526
AGAP002867 CYP6P4    amp                                   0.000000
AGAP002868 CYP6P1    amp                                   0.000000
AGAP008217 CYP6Z3    amp                                   0.000000
AGAP008218 CYP6Z2    amp                                   0.105263
                     del                                   0.000000
AGAP000818 CYP9K1    amp                                   0.105263
AGAP009195 GSTE1     amp                                   0.526316
AGAP009194 GSTE2     amp                                   0.526316

                               frq_GM-U_Basse_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                       0.200000
AGAP002862 CYP6AA1   amp                       0.200000
AGAP013128 CYP6AA2   amp                       0.066667
AGAP002867 CYP6P4    amp                       0.000000
AGAP002868 CYP6P1    amp                       0.000000
AGAP008217 CYP6Z3    amp                       0.000000
AGAP008218 CYP6Z2    amp                       0.066667
                     del                       0.000000
AGAP000818 CYP9K1    amp                       0.066667
AGAP009195 GSTE1     amp                       0.800000
AGAP009194 GSTE2     amp                       0.800000

                               frq_GM-U_Jimara_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                          0.3750
AGAP002862 CYP6AA1   amp                          0.1250
AGAP013128 CYP6AA2   amp                          0.0625
AGAP002867 CYP6P4    amp                          0.0000
AGAP002868 CYP6P1    amp                          0.0000
AGAP008217 CYP6Z3    amp                          0.0000
AGAP008218 CYP6Z2    amp                          0.1250
                     del                          0.0000
AGAP000818 CYP9K1    amp                          0.0625
AGAP009195 GSTE1     amp                          0.6250
AGAP009194 GSTE2     amp                          0.6250

                               frq_GM-W_Jeshwang_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                          0.617021
AGAP002862 CYP6AA1   amp                          0.744681
AGAP013128 CYP6AA2   amp                          0.744681
AGAP002867 CYP6P4    amp                          0.021277
AGAP002868 CYP6P1    amp                          0.021277
AGAP008217 CYP6Z3    amp                          0.021277
AGAP008218 CYP6Z2    amp                          0.659574
                     del                          0.000000
AGAP000818 CYP9K1    amp                          0.893617
AGAP009195 GSTE1     amp                          0.936170
AGAP009194 GSTE2     amp                          0.936170

                               frq_GM-W_Kombo-Central_arab_2019    max_af  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                                    0.8  0.800000
AGAP002862 CYP6AA1   amp                                    0.6  0.744681
AGAP013128 CYP6AA2   amp                                    0.6  0.744681
AGAP002867 CYP6P4    amp                                    0.1  0.100000
AGAP002868 CYP6P1    amp                                    0.1  0.100000
AGAP008217 CYP6Z3    amp                                    0.0  0.021277
AGAP008218 CYP6Z2    amp                                    0.3  0.659574
                     del                                    0.1  0.100000
AGAP000818 CYP9K1    amp                                    0.9  0.900000
AGAP009195 GSTE1     amp                                    0.8  0.936170
AGAP009194 GSTE2     amp                                    0.8  0.936170

                               windows                     label
gene_id    gene_name cnv_type
AGAP003645 NaN       del            64            AGAP003645 del
AGAP002862 CYP6AA1   amp             8  AGAP002862 (CYP6AA1) amp
AGAP013128 CYP6AA2   amp             6  AGAP013128 (CYP6AA2) amp
AGAP002867 CYP6P4    amp             6   AGAP002867 (CYP6P4) amp
AGAP002868 CYP6P1    amp             6   AGAP002868 (CYP6P1) amp
AGAP008217 CYP6Z3    amp             7   AGAP008217 (CYP6Z3) amp
AGAP008218 CYP6Z2    amp             7   AGAP008218 (CYP6Z2) amp
                     del             7   AGAP008218 (CYP6Z2) del
AGAP000818 CYP9K1    amp             9   AGAP000818 (CYP9K1) amp
AGAP009195 GSTE1     amp             4    AGAP009195 (GSTE1) amp
AGAP009194 GSTE2     amp             4    AGAP009194 (GSTE2) amp

In [ ]:
# define and select frequency_columns variable
frequency_columns = [
    col for col in df_cyp_keap_gste_cnv_freq.columns
    if col.startswith("frq_")
]
frequency_columns

['frq_GM-M_Lower-Fuladu-West_arab_2019',
 'frq_GM-U_Basse_arab_2019',
 'frq_GM-U_Jimara_arab_2019',
 'frq_GM-W_Jeshwang_arab_2019',
 'frq_GM-W_Kombo-Central_arab_2019']

In [ ]:
# To display the DataFrame selecting the defined frequency_columns + Max_af and windows columns
#gene_id , gene_name and cnv_type are index
df_cyp_keap_gste_cnv_freq[frequency_columns + ["max_af", "windows"]]

                               frq_GM-M_Lower-Fuladu-West_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                                   0.421053
AGAP002862 CYP6AA1   amp                                   0.210526
AGAP013128 CYP6AA2   amp                                   0.210526
AGAP002867 CYP6P4    amp                                   0.000000
AGAP002868 CYP6P1    amp                                   0.000000
AGAP008217 CYP6Z3    amp                                   0.000000
AGAP008218 CYP6Z2    amp                                   0.105263
                     del                                   0.000000
AGAP000818 CYP9K1    amp                                   0.105263
AGAP009195 GSTE1     amp                                   0.526316
AGAP009194 GSTE2     amp                                   0.526316

                               frq_GM-U_Basse_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                       0.200000
AGAP002862 CYP6AA1   amp                       0.200000
AGAP013128 CYP6AA2   amp                       0.066667
AGAP002867 CYP6P4    amp                       0.000000
AGAP002868 CYP6P1    amp                       0.000000
AGAP008217 CYP6Z3    amp                       0.000000
AGAP008218 CYP6Z2    amp                       0.066667
                     del                       0.000000
AGAP000818 CYP9K1    amp                       0.066667
AGAP009195 GSTE1     amp                       0.800000
AGAP009194 GSTE2     amp                       0.800000

                               frq_GM-U_Jimara_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                          0.3750
AGAP002862 CYP6AA1   amp                          0.1250
AGAP013128 CYP6AA2   amp                          0.0625
AGAP002867 CYP6P4    amp                          0.0000
AGAP002868 CYP6P1    amp                          0.0000
AGAP008217 CYP6Z3    amp                          0.0000
AGAP008218 CYP6Z2    amp                          0.1250
                     del                          0.0000
AGAP000818 CYP9K1    amp                          0.0625
AGAP009195 GSTE1     amp                          0.6250
AGAP009194 GSTE2     amp                          0.6250

                               frq_GM-W_Jeshwang_arab_2019  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                          0.617021
AGAP002862 CYP6AA1   amp                          0.744681
AGAP013128 CYP6AA2   amp                          0.744681
AGAP002867 CYP6P4    amp                          0.021277
AGAP002868 CYP6P1    amp                          0.021277
AGAP008217 CYP6Z3    amp                          0.021277
AGAP008218 CYP6Z2    amp                          0.659574
                     del                          0.000000
AGAP000818 CYP9K1    amp                          0.893617
AGAP009195 GSTE1     amp                          0.936170
AGAP009194 GSTE2     amp                          0.936170

                               frq_GM-W_Kombo-Central_arab_2019    max_af  \
gene_id    gene_name cnv_type
AGAP003645 NaN       del                                    0.8  0.800000
AGAP002862 CYP6AA1   amp                                    0.6  0.744681
AGAP013128 CYP6AA2   amp                                    0.6  0.744681
AGAP002867 CYP6P4    amp                                    0.1  0.100000
AGAP002868 CYP6P1    amp                                    0.1  0.100000
AGAP008217 CYP6Z3    amp                                    0.0  0.021277
AGAP008218 CYP6Z2    amp                                    0.3  0.659574
                     del                                    0.1  0.100000
AGAP000818 CYP9K1    amp                                    0.9  0.900000
AGAP009195 GSTE1     amp                                    0.8  0.936170
AGAP009194 GSTE2     amp                                    0.8  0.936170

                               windows
gene_id    gene_name cnv_type
AGAP003645 NaN       del            64
AGAP002862 CYP6AA1   amp             8
AGAP013128 CYP6AA2   amp             6
AGAP002867 CYP6P4    amp             6
AGAP002868 CYP6P1    amp             6
AGAP008217 CYP6Z3    amp             7
AGAP008218 CYP6Z2    amp             7
                     del             7
AGAP000818 CYP9K1    amp             9
AGAP009195 GSTE1     amp             4
AGAP009194 GSTE2     amp             4

In [ ]:
df_cyp_keap_gste_cnv_freq.columns

Index(['gene_strand', 'gene_description', 'contig', 'start', 'end',
       'frq_GM-M_Lower-Fuladu-West_arab_2019', 'frq_GM-U_Basse_arab_2019',
       'frq_GM-U_Jimara_arab_2019', 'frq_GM-W_Jeshwang_arab_2019',
       'frq_GM-W_Kombo-Central_arab_2019', 'max_af', 'windows', 'label'],
      dtype='object')

In [ ]:
arab_cnv_cohorts_admin2_year = [ #to plot it following the geographical alignement of the cohorts
    "GM-W_Jeshwang_arab_2019",
    "GM-W_Kombo-Central_arab_2019",
    "GM-M_Lower-Fuladu-West_arab_2019",
    "GM-U_Jimara_arab_2019",
    "GM-U_Basse_arab_2019"
]

In [ ]:
ag3.plot_frequencies_heatmap(
    df_cyp_keap_gste_cnv_freq .query("max_af >= 0.00")[["label"] + [f"frq_{c}" for c in arab_cnv_cohorts_admin2_year]],
    height=600, width=800,
    title="Gene CNV frequencies, Keap1(AGAP003645)+ Cyp6aa/p + Cyp9k1 + Cym6mz + gst1/2"
)

In [ ]:
ag3.plot_frequencies_heatmap(
    df_cyp_keap_gste_cnv_freq.query("max_af >= 0.00")[["label"] + [f"frq_{c}" for c in arab_cnv_cohorts_admin2_year]],
    height=600, width=700, color_continuous_scale = "turbo",
    title="Gene CNV frequencies, Keap1(AGAP003645)+ Cyp6aa/p + Cyp9k1 + Cym6mz + gst1/2",
)

In [ ]:
##################Supplementary Figure S4a ##################

# Rename the specific label in the DataFrame
df_cyp_keap_gste_cnv_freq['label'] = df_cyp_keap_gste_cnv_freq['label'].replace(
    'AGAP003645 del', 'AGAP003645 (Keap1) del'
)
# Lets increase the size of the legends for better displaying !!!
fig = ag3.plot_frequencies_heatmap (
   df_cyp_keap_gste_cnv_freq.query("max_af >= 0.00")[["label"] + [f"frq_{c}" for c in arab_cnv_cohorts_admin2_year]],
    height=700,
    width=850,
    color_continuous_scale="turbo", #["lightblue", "purple"]
    title="Gene CNV frequencies, Keap1 + Cyp6aa/p + Cyp9k1 + Cym6mz + gste1/2",
    show=False, # Set show=False to return the figure object for modification
)

# Increase colorbar legend font size (title and tick labels) and text inside cells font size
fig.update_layout(
    legend=dict(
       font=dict(size=16),
    ),
    coloraxis_colorbar=dict(
        title_font=dict(size=16), # Adjust colorbar title font size
        tickfont=dict(size=16)   # Adjust colorbar tick label font size
    ),
    xaxis=dict( # Update x-axis properties for cohorts
        tickfont=dict(size=16), # Adjust font size for x-axis tick labels (cohorts) - Increased size
        title_font=dict(size=16) # Adjust font size for x-axis title
    ),
    yaxis=dict( # Update y-axis properties for variants
        tickfont=dict(size=16), # Adjust font size for y-axis tick labels (variants) - Increased size
        title_font=dict(size=16) # Adjust font size for y-axis title
    )
)

# Set the font size for the text inside the heatmap cells
fig.data[0].textfont = dict(size=16
                            )

# Display the modified figure
fig.show()

### **COE locus CNV Freq -- Supplementary Figure S4b**

In [ ]:
COE_region = "2L:37,233,000-37,330,000"

In [ ]:
df_COE_cnv_freq = ag3.gene_cnv_frequencies(
    sample_query="country == 'Gambia, The' and taxon == 'arabiensis' and release == '3.5'",
    cohorts="admin2_year",
    region=COE_region,
    sample_sets="3.5",  # needed because CNV data not released for 3.1
   # drop_invariant=False,
)
df_COE_cnv_freq

Load CNV HMM data:   0%|          | 0/49 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/12 [00:00<?, ?it/s]

                              gene_strand  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                +
AGAP006723 COEAE2G   amp                -
AGAP006724 COEAE3G   amp                -
AGAP006725 COEAE3H   amp                -
AGAP006726 COEAE5G   amp                +
AGAP006727 COEAE6G   amp                -
AGAP006728 COEAE7G   amp                +
AGAP006729 NaN       amp                -
AGAP006730 NaN       amp                -
AGAP029696 NaN       amp                -
                     del                -
AGAP029697 NaN       amp                +
                     del                +

                                                                gene_description  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp       cecropin anti-microbial peptide [Source:VB Com...
AGAP006723 COEAE2G   amp       carboxylesterase [Source:VB Community Annotation]
AGAP006724 COEAE3G   amp       carboxylesterase [Source:VB Community Annotation]
AGAP006725 COEAE3H   amp       carboxylesterase alpha esterase [Source:VB Com...
AGAP006726 COEAE5G   amp       carboxylesterase [Source:VB Community Annotation]
AGAP006727 COEAE6G   amp       carboxylesterase [Source:VB Community Annotation]
AGAP006728 COEAE7G   amp       carboxylesterase [Source:VB Community Annotation]
AGAP006729 NaN       amp       Ester hydrolase C11orf54 [Source:VB Community ...
AGAP006730 NaN       amp                                                     NaN
AGAP029696 NaN       amp                                                     NaN
                     del                                                     NaN
AGAP029697 NaN       amp                                                     NaN
                     del                                                     NaN

                              contig     start       end  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp          2L  37233354  37233690
AGAP006723 COEAE2G   amp          2L  37282152  37285191
AGAP006724 COEAE3G   amp          2L  37285915  37288160
AGAP006725 COEAE3H   amp          2L  37288762  37290797
AGAP006726 COEAE5G   amp          2L  37291002  37292961
AGAP006727 COEAE6G   amp          2L  37292956  37295490
AGAP006728 COEAE7G   amp          2L  37296161  37298202
AGAP006729 NaN       amp          2L  37298235  37299911
AGAP006730 NaN       amp          2L  37301781  37306179
AGAP029696 NaN       amp          2L  37315119  37318526
                     del          2L  37315119  37318526
AGAP029697 NaN       amp          2L  37327355  37328305
                     del          2L  37327355  37328305

                               frq_GM-M_Lower-Fuladu-West_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                                   0.315789
AGAP006723 COEAE2G   amp                                   0.315789
AGAP006724 COEAE3G   amp                                   0.315789
AGAP006725 COEAE3H   amp                                   0.631579
AGAP006726 COEAE5G   amp                                   0.631579
AGAP006727 COEAE6G   amp                                   0.631579
AGAP006728 COEAE7G   amp                                   0.631579
AGAP006729 NaN       amp                                   0.631579
AGAP006730 NaN       amp                                   0.315789
AGAP029696 NaN       amp                                   0.052632
                     del                                   0.315789
AGAP029697 NaN       amp                                   0.052632
                     del                                   0.894737

                               frq_GM-U_Basse_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                       0.200000
AGAP006723 COEAE2G   amp                       0.200000
AGAP006724 COEAE3G   amp                       0.200000
AGAP006725 COEAE3H   amp                       0.600000
AGAP006726 COEAE5G   amp                       0.600000
AGAP006727 COEAE6G   amp                       0.600000
AGAP006728 COEAE7G   amp                       0.600000
AGAP006729 NaN       amp                       0.600000
AGAP006730 NaN       amp                       0.200000
AGAP029696 NaN       amp                       0.266667
                     del                       0.266667
AGAP029697 NaN       amp                       0.000000
                     del                       0.933333

                               frq_GM-U_Jimara_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                          0.3750
AGAP006723 COEAE2G   amp                          0.3750
AGAP006724 COEAE3G   amp                          0.4375
AGAP006725 COEAE3H   amp                          0.8125
AGAP006726 COEAE5G   amp                          0.8125
AGAP006727 COEAE6G   amp                          0.8125
AGAP006728 COEAE7G   amp                          0.8125
AGAP006729 NaN       amp                          0.8125
AGAP006730 NaN       amp                          0.3125
AGAP029696 NaN       amp                          0.2500
                     del                          0.2500
AGAP029697 NaN       amp                          0.1250
                     del                          0.8125

                               frq_GM-W_Jeshwang_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                          0.829787
AGAP006723 COEAE2G   amp                          0.829787
AGAP006724 COEAE3G   amp                          0.829787
AGAP006725 COEAE3H   amp                          0.978723
AGAP006726 COEAE5G   amp                          0.978723
AGAP006727 COEAE6G   amp                          0.978723
AGAP006728 COEAE7G   amp                          0.978723
AGAP006729 NaN       amp                          0.978723
AGAP006730 NaN       amp                          0.808511
AGAP029696 NaN       amp                          0.085106
                     del                          0.744681
AGAP029697 NaN       amp                          0.106383
                     del                          0.872340

                               frq_GM-W_Kombo-Central_arab_2019    max_af  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                                    0.5  0.829787
AGAP006723 COEAE2G   amp                                    0.5  0.829787
AGAP006724 COEAE3G   amp                                    0.5  0.829787
AGAP006725 COEAE3H   amp                                    1.0  1.000000
AGAP006726 COEAE5G   amp                                    1.0  1.000000
AGAP006727 COEAE6G   amp                                    1.0  1.000000
AGAP006728 COEAE7G   amp                                    1.0  1.000000
AGAP006729 NaN       amp                                    1.0  1.000000
AGAP006730 NaN       amp                                    0.5  0.808511
AGAP029696 NaN       amp                                    0.0  0.266667
                     del                                    0.8  0.800000
AGAP029697 NaN       amp                                    0.0  0.125000
                     del                                    1.0  1.000000

                               windows                     label
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp             2     AGAP006722 (CEC4) amp
AGAP006723 COEAE2G   amp            11  AGAP006723 (COEAE2G) amp
AGAP006724 COEAE3G   amp             8  AGAP006724 (COEAE3G) amp
AGAP006725 COEAE3H   amp             8  AGAP006725 (COEAE3H) amp
AGAP006726 COEAE5G   amp             7  AGAP006726 (COEAE5G) amp
AGAP006727 COEAE6G   amp            10  AGAP006727 (COEAE6G) amp
AGAP006728 COEAE7G   amp             8  AGAP006728 (COEAE7G) amp
AGAP006729 NaN       amp             7            AGAP006729 amp
AGAP006730 NaN       amp            15            AGAP006730 amp
AGAP029696 NaN       amp            13            AGAP029696 amp
                     del            13            AGAP029696 del
AGAP029697 NaN       amp             4            AGAP029697 amp
                     del             4            AGAP029697 del

In [ ]:
# define and select frequency_columns variable
frequency_columns = [
    col for col in df_COE_cnv_freq.columns
    if col.startswith("frq_")
]
frequency_columns

['frq_GM-M_Lower-Fuladu-West_arab_2019',
 'frq_GM-U_Basse_arab_2019',
 'frq_GM-U_Jimara_arab_2019',
 'frq_GM-W_Jeshwang_arab_2019',
 'frq_GM-W_Kombo-Central_arab_2019']

In [ ]:
# To display the DataFrame selecting the defined frequency_columns + Max_af and windows columns
#gene_id , gene_name and cnv_type are index
df_COE_cnv_freq[frequency_columns + ["max_af", "windows"]]

                               frq_GM-M_Lower-Fuladu-West_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                                   0.315789
AGAP006723 COEAE2G   amp                                   0.315789
AGAP006724 COEAE3G   amp                                   0.315789
AGAP006725 COEAE3H   amp                                   0.631579
AGAP006726 COEAE5G   amp                                   0.631579
AGAP006727 COEAE6G   amp                                   0.631579
AGAP006728 COEAE7G   amp                                   0.631579
AGAP006729 NaN       amp                                   0.631579
AGAP006730 NaN       amp                                   0.315789
AGAP029696 NaN       amp                                   0.052632
                     del                                   0.315789
AGAP029697 NaN       amp                                   0.052632
                     del                                   0.894737

                               frq_GM-U_Basse_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                       0.200000
AGAP006723 COEAE2G   amp                       0.200000
AGAP006724 COEAE3G   amp                       0.200000
AGAP006725 COEAE3H   amp                       0.600000
AGAP006726 COEAE5G   amp                       0.600000
AGAP006727 COEAE6G   amp                       0.600000
AGAP006728 COEAE7G   amp                       0.600000
AGAP006729 NaN       amp                       0.600000
AGAP006730 NaN       amp                       0.200000
AGAP029696 NaN       amp                       0.266667
                     del                       0.266667
AGAP029697 NaN       amp                       0.000000
                     del                       0.933333

                               frq_GM-U_Jimara_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                          0.3750
AGAP006723 COEAE2G   amp                          0.3750
AGAP006724 COEAE3G   amp                          0.4375
AGAP006725 COEAE3H   amp                          0.8125
AGAP006726 COEAE5G   amp                          0.8125
AGAP006727 COEAE6G   amp                          0.8125
AGAP006728 COEAE7G   amp                          0.8125
AGAP006729 NaN       amp                          0.8125
AGAP006730 NaN       amp                          0.3125
AGAP029696 NaN       amp                          0.2500
                     del                          0.2500
AGAP029697 NaN       amp                          0.1250
                     del                          0.8125

                               frq_GM-W_Jeshwang_arab_2019  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                          0.829787
AGAP006723 COEAE2G   amp                          0.829787
AGAP006724 COEAE3G   amp                          0.829787
AGAP006725 COEAE3H   amp                          0.978723
AGAP006726 COEAE5G   amp                          0.978723
AGAP006727 COEAE6G   amp                          0.978723
AGAP006728 COEAE7G   amp                          0.978723
AGAP006729 NaN       amp                          0.978723
AGAP006730 NaN       amp                          0.808511
AGAP029696 NaN       amp                          0.085106
                     del                          0.744681
AGAP029697 NaN       amp                          0.106383
                     del                          0.872340

                               frq_GM-W_Kombo-Central_arab_2019    max_af  \
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp                                    0.5  0.829787
AGAP006723 COEAE2G   amp                                    0.5  0.829787
AGAP006724 COEAE3G   amp                                    0.5  0.829787
AGAP006725 COEAE3H   amp                                    1.0  1.000000
AGAP006726 COEAE5G   amp                                    1.0  1.000000
AGAP006727 COEAE6G   amp                                    1.0  1.000000
AGAP006728 COEAE7G   amp                                    1.0  1.000000
AGAP006729 NaN       amp                                    1.0  1.000000
AGAP006730 NaN       amp                                    0.5  0.808511
AGAP029696 NaN       amp                                    0.0  0.266667
                     del                                    0.8  0.800000
AGAP029697 NaN       amp                                    0.0  0.125000
                     del                                    1.0  1.000000

                               windows
gene_id    gene_name cnv_type
AGAP006722 CEC4      amp             2
AGAP006723 COEAE2G   amp            11
AGAP006724 COEAE3G   amp             8
AGAP006725 COEAE3H   amp             8
AGAP006726 COEAE5G   amp             7
AGAP006727 COEAE6G   amp            10
AGAP006728 COEAE7G   amp             8
AGAP006729 NaN       amp             7
AGAP006730 NaN       amp            15
AGAP029696 NaN       amp            13
                     del            13
AGAP029697 NaN       amp             4
                     del             4

In [ ]:
df_COE_cnv_freq.columns

Index(['gene_strand', 'gene_description', 'contig', 'start', 'end',
       'frq_GM-M_Lower-Fuladu-West_arab_2019', 'frq_GM-U_Basse_arab_2019',
       'frq_GM-U_Jimara_arab_2019', 'frq_GM-W_Jeshwang_arab_2019',
       'frq_GM-W_Kombo-Central_arab_2019', 'max_af', 'windows', 'label'],
      dtype='object')

In [ ]:
arab_cnv_cohorts_admin2_year = [ #to plot it following the geographical alignement of the cohorts
    "GM-W_Jeshwang_arab_2019",
    "GM-W_Kombo-Central_arab_2019",
    "GM-M_Lower-Fuladu-West_arab_2019",
    "GM-U_Jimara_arab_2019",
    "GM-U_Basse_arab_2019"
]

In [ ]:
##### Supplementary Figure S4b ###########
# Lets increase the size of the legends for better displaying !!!
fig = ag3.plot_frequencies_heatmap (
   df_COE_cnv_freq.query("max_af >= 0.00")[["label"] + [f"frq_{c}" for c in arab_cnv_cohorts_admin2_year]],
    height=675,
    width=850,
    # Change the colorscale to a valid name from the list provided in the error message
    color_continuous_scale="turbo",
    title="Gene CNV frequencies,COE locus",
    show=False, # Set show=False to return the figure object for modification
)

# Increase colorbar legend font size (title and tick labels) and text inside cells font size
fig.update_layout(
    legend=dict(
       font=dict(size=16),
    ),
    coloraxis_colorbar=dict(
        title_font=dict(size=16), # Adjust colorbar title font size
        tickfont=dict(size=16)   # Adjust colorbar tick label font size
    ),
    xaxis=dict( # Update x-axis properties for cohorts
        tickfont=dict(size=16), # Adjust font size for x-axis tick labels (cohorts) - Increased size
        title_font=dict(size=16) # Adjust font size for x-axis title
    ),
    yaxis=dict( # Update y-axis properties for variants
        tickfont=dict(size=16), # Adjust font size for y-axis tick labels (variants) - Increased size
        title_font=dict(size=16) # Adjust font size for y-axis title
    ),
    title_font=dict(size=16)
)

# Set the font size for the text inside the heatmap cells
fig.data[0].textfont = dict(size=16)

# Display the modified figure
fig.show()

### **COE locus CNV HMM -- Supplementary Figure S8**

In [35]:
ag3.plot_cnv_hmm_heatmap(
    region=COE_region,
    sample_query='taxon == "arabiensis"',
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
    row_height=2
)

GridPlot(id='p1116', ...)