# **Genomic analysis of malaria vectors in The Gambia**

### **Target-site resistance profile in _An. arabiensis_**

- In this notebook, we explore target-site resistance profile in *Anopheles arabiensis* in the Gambia

In [ ]:
!pip install -q malariagen_data

In [ ]:
!pip install -q "plotly<6" kaleido==0.2.1

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 5.8 MB/s eta 0:00:00

In [ ]:
import malariagen_data
import os
import kaleido
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import bokeh.io as bkio
bkio.output_notebook()

In [ ]:
try:
    from google.colab import drive, output
    output.enable_custom_widget_manager()
    drive.mount("drive")
    base_dir = "drive/MyDrive/Colab Data/gm-analysis"
except ImportError:
    base_dir = "../results/gm-analysis"

results_dir = os.path.join(base_dir, "Snp_Cnv_freq-results")

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

In [ ]:
results_dir

'drive/MyDrive/Colab Data/gm-analysis/Snp_Cnv_freq-results'

In [ ]:
git_dir = "/content/drive/My Drive/Colab Data/divergent-genetic-insecticide-resistance-in-gambian-malaria-vector"
try:
  figures_dir = os.path.join(git_dir, "figures")
except NameError:
  figures_dir = "../figures"
os.makedirs(results_dir, exist_ok=True)

In [ ]:
figures_dir

'/content/drive/My Drive/Colab Data/divergent-genetic-insecticide-resistance-in-gambian-malaria-vector/figures'

In [ ]:
ag3 = malariagen_data.Ag3()
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : gs://vo_agam_release_master_us_central1/
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
Results cache                         : None
Cohorts analysis                      : 20260120
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.10.0
Client location                       : South Carolina, United States (Google Cloud us-east1)
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
---
Please note that data are subject to terms of use,
for more information see the Vector Observatory website https://www.malariagen.net/vobs/
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.10.0/Ag3.html

In [ ]:
gambia_sample_query = "country == 'Gambia, The' and sample_set == '1272-VO-GM-OPONDO-VMF00160' and taxon == 'arabiensis' and sample_id!='VBS47740-6366STDY9854349' and unrestricted_use == True"

In [ ]:
# access metadata
df_samples_gambia = ag3.sample_metadata(sample_query=gambia_sample_query)
df_samples_gambia

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,VBS47723-6366STDY9854332,C0454,Kevin Opondo,"Gambia, The",Dongoroba,2019,9,13.380,-15.294,F,...,Mansakonko,GM-L,Jarra East,arabiensis,GM-L_arab_2019,GM-L_arab_2019_09,GM-L_arab_2019_Q3,GM-L_Jarra-East_arab_2019,GM-L_Jarra-East_arab_2019_09,GM-L_Jarra-East_arab_2019_Q3
1,VBS47725-6366STDY9854334,C2409,Kevin Opondo,"Gambia, The",Kerewan,2019,9,13.515,-14.896,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_09,GM-M_Lower-Fuladu-West_arab_2019_Q3
2,VBS47726-6366STDY9854335,C0587,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
3,VBS47729-6366STDY9854338,C2710,Kevin Opondo,"Gambia, The",Boiram,2019,10,13.503,-14.926,F,...,Janjanbureh,GM-M,Lower Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_10,GM-M_arab_2019_Q4,GM-M_Lower-Fuladu-West_arab_2019,GM-M_Lower-Fuladu-West_arab_2019_10,GM-M_Lower-Fuladu-West_arab_2019_Q4
4,VBS47731-6366STDY9854340,C2524,Kevin Opondo,"Gambia, The",Bansang,2019,9,13.434,-14.655,F,...,Janjanbureh,GM-M,Upper Fuladu West,arabiensis,GM-M_arab_2019,GM-M_arab_2019_09,GM-M_arab_2019_Q3,GM-M_Upper-Fuladu-West_arab_2019,GM-M_Upper-Fuladu-West_arab_2019_09,GM-M_Upper-Fuladu-West_arab_2019_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,VBS48167-6366STDY9854768,W1491,Kevin Opondo,"Gambia, The",Essau,2019,10,13.481,-16.515,F,...,Kerewan,GM-N,Lower Niumi,arabiensis,GM-N_arab_2019,GM-N_arab_2019_10,GM-N_arab_2019_Q4,GM-N_Lower-Niumi_arab_2019,GM-N_Lower-Niumi_arab_2019_10,GM-N_Lower-Niumi_arab_2019_Q4
310,VBS48171-6366STDY9854772,W2321,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3
311,VBS48173-6366STDY9854774,W0382,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
312,VBS48174-6366STDY9854775,W1168,Kevin Opondo,"Gambia, The",Tallinding,2019,9,13.437,-16.670,F,...,Kanifing,GM-W,Jeshwang,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Jeshwang_arab_2019,GM-W_Jeshwang_arab_2019_09,GM-W_Jeshwang_arab_2019_Q3
313,VBS48175-6366STDY9854776,W1807,Kevin Opondo,"Gambia, The",Brikama-A,2019,9,13.290,-16.657,F,...,Brikama,GM-W,Kombo Central,arabiensis,GM-W_arab_2019,GM-W_arab_2019_09,GM-W_arab_2019_Q3,GM-W_Kombo-Central_arab_2019,GM-W_Kombo-Central_arab_2019_09,GM-W_Kombo-Central_arab_2019_Q3

### **Figure 3. Pyrethroid target-site resistance**

- Vgsc gene target-site resistance - AGAP004707-RD

In [ ]:
df_samples_gambia.pivot_table(
    index=["admin1_name", "admin2_name", "year"],
    columns="taxon",
    values="sample_id",
    aggfunc="count",
    fill_value=0,
)

taxon                               arabiensis
admin1_name admin2_name       year
Basse       Basse             2019          28
            Jimara            2019          37
            Sandu             2019           8
            Tumana            2019          21
            Wuli East         2019           1
Brikama     Foni Brefet       2019           1
            Kombo Central     2019          28
Janjanbureh Lower Fuladu West 2019          51
            Niamina East      2019          10
            Niamina West      2019           8
            Upper Fuladu West 2019          12
Kanifing    Bakau             2019           6
            Jeshwang          2019          77
Kerewan     Illiasa           2019           3
            Lower Niumi       2019          13
Kuntaur     Niani             2019           4
Mansakonko  Jarra East        2019           6

In [ ]:
df_vgsc_freq_gambia = ag3.aa_allele_frequencies(
    transcript="AGAP004707-RD",
    sample_query=gambia_sample_query,
    cohorts="admin2_year",
)
df_vgsc_freq_gambia

Load SNP genotypes:   0%|          | 0/75 [00:00<?, ?it/s]

Compute allele frequencies:   0%|          | 0/9 [00:00<?, ?it/s]

Compute SNP effects:   0%|          | 0/19974 [00:00<?, ?it/s]

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
M1I,2L,2358160,0.009804,0.00,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,G,M,I,NON_SYNONYMOUS_CODING,MODERATE,10.0,20.0,T,0.009804,"M1I (2L:2,358,160 G>T)"
D6Y,2L,2358173,0.000000,0.05,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,G,D,Y,NON_SYNONYMOUS_CODING,MODERATE,160.0,34.0,T,0.050000,"D6Y (2L:2,358,173 G>T)"
E12*,2L,2358191,0.000000,0.00,0.0,0.038462,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,G,E,*,STOP_GAINED,HIGH,NaN,NaN,T,0.038462,"E12* (2L:2,358,191 G>T)"
F16L,2L,2358205,0.009804,0.00,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,C,F,L,NON_SYNONYMOUS_CODING,MODERATE,22.0,22.0,A,0.009804,"F16L (2L:2,358,205 C>A)"
R17S,2L,2358206,0.019608,0.00,0.0,0.038462,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,C,R,S,NON_SYNONYMOUS_CODING,MODERATE,110.0,37.0,A,0.038462,"R17S (2L:2,358,206 C>A)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V2103F,2L,2431567,0.000000,0.00,0.0,0.000000,0.0,0.0,0.02381,0.000000,0.0,AGAP004707-RD,...,G,V,F,NON_SYNONYMOUS_CODING,MODERATE,50.0,26.0,T,0.023810,"V2103F (2L:2,431,567 G>T)"
H2105Y,2L,2431573,0.009804,0.00,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,C,H,Y,NON_SYNONYMOUS_CODING,MODERATE,83.0,23.0,T,0.009804,"H2105Y (2L:2,431,573 C>T)"
S2108T,2L,2431582,0.009804,0.00,0.0,0.000000,0.0,0.0,0.00000,0.006494,0.0,AGAP004707-RD,...,T,S,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,12.0,A,0.009804,"S2108T (2L:2,431,582 T>A)"
V2118F,2L,2431612,0.009804,0.00,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,AGAP004707-RD,...,G,V,F,NON_SYNONYMOUS_CODING,MODERATE,50.0,26.0,T,0.009804,"V2118F (2L:2,431,612 G>T)"
*2119S,2L,2431616,0.000000,0.00,0.0,0.000000,0.0,0.0,0.02381,0.000000,0.0,AGAP004707-RD,...,G,*,S,STOP_LOST,HIGH,NaN,NaN,C,0.023810,"*2119S (2L:2,431,616 G>C)"

In [ ]:
ag3.plot_frequencies_heatmap(
    df_vgsc_freq_gambia.query("max_af > 0.05")
)

In [ ]:
df_vgsc_freq_gambia_admin2_year = (
    df_samples_gambia
    .groupby("cohort_admin2_year")
    .aggregate({
        "latitude": "mean",
        "longitude": "mean",
        "sample_id": "count",
    })
    .query("sample_id >= 10")
    .sort_values("longitude")
)
df_vgsc_freq_gambia_admin2_year

                                   latitude  longitude  sample_id
cohort_admin2_year
GM-W_Jeshwang_arab_2019           13.437247 -16.670987         77
GM-W_Kombo-Central_arab_2019      13.290000 -16.657000         28
GM-N_Lower-Niumi_arab_2019        13.481000 -16.515000         13
GM-M_Niamina-East_arab_2019       13.619500 -15.157000         10
GM-M_Lower-Fuladu-West_arab_2019  13.530882 -14.902039         51
GM-M_Upper-Fuladu-West_arab_2019  13.434000 -14.655000         12
GM-U_Jimara_arab_2019             13.275973 -14.324162         37
GM-U_Basse_arab_2019              13.269286 -14.205750         28
GM-U_Tumana_arab_2019             13.355952 -14.049190         21

In [ ]:
all_cohorts_admin2_year = df_vgsc_freq_gambia_admin2_year.index.tolist()
all_cohorts_admin2_year

['GM-W_Jeshwang_arab_2019',
 'GM-W_Kombo-Central_arab_2019',
 'GM-N_Lower-Niumi_arab_2019',
 'GM-M_Niamina-East_arab_2019',
 'GM-M_Lower-Fuladu-West_arab_2019',
 'GM-M_Upper-Fuladu-West_arab_2019',
 'GM-U_Jimara_arab_2019',
 'GM-U_Basse_arab_2019',
 'GM-U_Tumana_arab_2019']

In [ ]:
ag3.plot_frequencies_heatmap(
    df_vgsc_freq_gambia.query("max_af > 0.05")[["label"] + [f"frq_{c}" for c in all_cohorts_admin2_year]]
)

In [ ]:
frequency_columns = [
    col for col in df_vgsc_freq_gambia.columns
    if col.startswith("frq_")
]
frequency_columns

['frq_GM-M_Lower-Fuladu-West_arab_2019',
 'frq_GM-M_Niamina-East_arab_2019',
 'frq_GM-M_Upper-Fuladu-West_arab_2019',
 'frq_GM-N_Lower-Niumi_arab_2019',
 'frq_GM-U_Basse_arab_2019',
 'frq_GM-U_Jimara_arab_2019',
 'frq_GM-U_Tumana_arab_2019',
 'frq_GM-W_Jeshwang_arab_2019',
 'frq_GM-W_Kombo-Central_arab_2019']

In [ ]:
vgsc_aa_effect_df = df_vgsc_freq_gambia[["effect", "impact"]]
vgsc_aa_effect_df

                                          effect    impact
aa_change contig position
M1I       2L     2358160   NON_SYNONYMOUS_CODING  MODERATE
D6Y       2L     2358173   NON_SYNONYMOUS_CODING  MODERATE
E12*      2L     2358191             STOP_GAINED      HIGH
F16L      2L     2358205   NON_SYNONYMOUS_CODING  MODERATE
R17S      2L     2358206   NON_SYNONYMOUS_CODING  MODERATE
...                                          ...       ...
V2103F    2L     2431567   NON_SYNONYMOUS_CODING  MODERATE
H2105Y    2L     2431573   NON_SYNONYMOUS_CODING  MODERATE
S2108T    2L     2431582   NON_SYNONYMOUS_CODING  MODERATE
V2118F    2L     2431612   NON_SYNONYMOUS_CODING  MODERATE
*2119S    2L     2431616               STOP_LOST      HIGH

[1015 rows x 2 columns]

In [ ]:
arab_cohorts_admin2_year_gambia = (
    df_samples_gambia
    .query("taxon == 'arabiensis'")
    .groupby("cohort_admin2_year")
    .aggregate({
        "latitude": "mean",
        "longitude": "mean",
        "sample_id": "count",
    })
    .query("sample_id >= 10")
    .sort_values("longitude")
)
arab_cohorts_admin2_year_gambia

                                   latitude  longitude  sample_id
cohort_admin2_year
GM-W_Jeshwang_arab_2019           13.437247 -16.670987         77
GM-W_Kombo-Central_arab_2019      13.290000 -16.657000         28
GM-N_Lower-Niumi_arab_2019        13.481000 -16.515000         13
GM-M_Niamina-East_arab_2019       13.619500 -15.157000         10
GM-M_Lower-Fuladu-West_arab_2019  13.530882 -14.902039         51
GM-M_Upper-Fuladu-West_arab_2019  13.434000 -14.655000         12
GM-U_Jimara_arab_2019             13.275973 -14.324162         37
GM-U_Basse_arab_2019              13.269286 -14.205750         28
GM-U_Tumana_arab_2019             13.355952 -14.049190         21

In [ ]:
arab_cohorts_admin2_year = arab_cohorts_admin2_year_gambia.index.tolist()
arab_cohorts_admin2_year

['GM-W_Jeshwang_arab_2019',
 'GM-W_Kombo-Central_arab_2019',
 'GM-N_Lower-Niumi_arab_2019',
 'GM-M_Niamina-East_arab_2019',
 'GM-M_Lower-Fuladu-West_arab_2019',
 'GM-M_Upper-Fuladu-West_arab_2019',
 'GM-U_Jimara_arab_2019',
 'GM-U_Basse_arab_2019',
 'GM-U_Tumana_arab_2019']

In [ ]:
ag3.plot_frequencies_heatmap(
    df_vgsc_freq_gambia.query("max_af > 0.05")[["label"] + [f"frq_{c}" for c in arab_cohorts_admin2_year]],
    row_height=30,
    color_continuous_scale='Turbo'
)

In [ ]:
ag3.plot_frequencies_heatmap(
    df_vgsc_freq_gambia.query("max_af >= 0.05")[["label"] + [f"frq_{c}" for c in arab_cohorts_admin2_year]],
    row_height=30,
    color_continuous_scale='Turbo'
)

### **Glutathione-S-transferases target-site resistance (GSTs)**

In [ ]:
df_gst_freq_gambia = ag3.aa_allele_frequencies(
    transcript="AGAP009194-RA",
    sample_query=gambia_sample_query,
    cohorts="admin2_year",
)
df_gst_freq_gambia

Load SNP genotypes:   0%|          | 0/38 [00:00<?, ?it/s]

Compute allele frequencies:   0%|          | 0/9 [00:00<?, ?it/s]

Compute SNP effects:   0%|          | 0/146 [00:00<?, ?it/s]

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
A213T,3R,28597780,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,C,A,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,T,0.009804,"A213T (3R:28,597,780 C>T)"
T205I,3R,28597803,0.000000,0.00,0.000000,0.000000,0.000000,0.013514,0.000000,0.006494,0.017857,AGAP009194-RA,...,G,T,I,NON_SYNONYMOUS_CODING,MODERATE,89.0,23.0,A,0.017857,"T205I (3R:28,597,803 G>A)"
P194H,3R,28597836,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,P,H,NON_SYNONYMOUS_CODING,MODERATE,77.0,36.0,T,0.009804,"P194H (3R:28,597,836 G>T)"
A185T,3R,28597864,0.225490,0.15,0.250000,0.038462,0.107143,0.216216,0.119048,0.045455,0.125000,AGAP009194-RA,...,C,A,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,T,0.250000,"A185T (3R:28,597,864 C>T)"
P181H,3R,28597875,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,P,H,NON_SYNONYMOUS_CODING,MODERATE,77.0,36.0,T,0.009804,"P181H (3R:28,597,875 G>T)"
S178*,3R,28597884,0.000000,0.00,0.000000,0.000000,0.000000,0.013514,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,S,*,STOP_GAINED,HIGH,NaN,NaN,T,0.013514,"S178* (3R:28,597,884 G>T)"
S178L,3R,28597884,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.006494,0.000000,AGAP009194-RA,...,G,S,L,NON_SYNONYMOUS_CODING,MODERATE,145.0,25.0,A,0.006494,"S178L (3R:28,597,884 G>A)"
E176A,3R,28597890,0.000000,0.00,0.000000,0.000000,0.000000,0.013514,0.000000,0.000000,0.000000,AGAP009194-RA,...,T,E,A,NON_SYNONYMOUS_CODING,MODERATE,107.0,34.0,G,0.013514,"E176A (3R:28,597,890 T>G)"
E176K,3R,28597891,0.009804,0.00,0.041667,0.000000,0.000000,0.000000,0.000000,0.006494,0.000000,AGAP009194-RA,...,C,E,K,NON_SYNONYMOUS_CODING,MODERATE,95.0,26.0,T,0.041667,"E176K (3R:28,597,891 C>T)"
P174L,3R,28597896,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,P,L,NON_SYNONYMOUS_CODING,MODERATE,98.0,24.0,A,0.009804,"P174L (3R:28,597,896 G>A)"
P174S,3R,28597897,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,P,S,NON_SYNONYMOUS_CODING,MODERATE,74.0,24.0,A,0.009804,"P174S (3R:28,597,897 G>A)"
I163L,3R,28597930,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,T,I,L,NON_SYNONYMOUS_CODING,MODERATE,5.0,5.0,G,0.050000,"I163L (3R:28,597,930 T>G)"
T154S,3R,28597956,0.852941,0.90,0.833333,0.961538,0.857143,0.891892,0.904762,0.980519,0.821429,AGAP009194-RA,...,G,T,S,NON_SYNONYMOUS_CODING,MODERATE,58.0,12.0,C,0.980519,"T154S (3R:28,597,956 G>C)"
D143E,3R,28597988,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,D,E,NON_SYNONYMOUS_CODING,MODERATE,160.0,7.0,T,0.009804,"D143E (3R:28,597,988 G>T)"
E139K,3R,28598002,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,C,E,K,NON_SYNONYMOUS_CODING,MODERATE,95.0,26.0,T,0.009804,"E139K (3R:28,598,002 C>T)"
I126F,3R,28598041,0.000000,0.00,0.041667,0.000000,0.017857,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,T,I,F,NON_SYNONYMOUS_CODING,MODERATE,21.0,19.0,A,0.041667,"I126F (3R:28,598,041 T>A)"
S98A,3R,28598215,0.166667,0.10,0.208333,0.000000,0.214286,0.162162,0.142857,0.006494,0.089286,AGAP009194-RA,...,A,S,A,NON_SYNONYMOUS_CODING,MODERATE,99.0,16.0,C,0.214286,"S98A (3R:28,598,215 A>C)"
V91I,3R,28598236,0.039216,0.05,0.083333,0.038462,0.017857,0.054054,0.047619,0.006494,0.000000,AGAP009194-RA,...,C,V,I,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,T,0.083333,"V91I (3R:28,598,236 C>T)"
L85V,3R,28598254,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,L,V,NON_SYNONYMOUS_CODING,MODERATE,32.0,7.0,C,0.050000,"L85V (3R:28,598,254 G>C)"
S84R,3R,28598255,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,S,R,NON_SYNONYMOUS_CODING,MODERATE,110.0,37.0,C,0.009804,"S84R (3R:28,598,255 G>C)"
G80S,3R,28598269,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.023810,0.000000,0.000000,AGAP009194-RA,...,C,G,S,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,T,0.023810,"G80S (3R:28,598,269 C>T)"
M72I,3R,28598291,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,C,M,I,NON_SYNONYMOUS_CODING,MODERATE,10.0,20.0,T,0.009804,"M72I (3R:28,598,291 C>T)"
N61K,3R,28598324,0.000000,0.00,0.000000,0.000000,0.000000,0.013514,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,N,K,NON_SYNONYMOUS_CODING,MODERATE,23.0,27.0,T,0.013514,"N61K (3R:28,598,324 G>T)"
D60Y,3R,28598329,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.023810,0.000000,0.000000,AGAP009194-RA,...,C,D,Y,NON_SYNONYMOUS_CODING,MODERATE,160.0,34.0,A,0.023810,"D60Y (3R:28,598,329 C>A)"
P56Q,3R,28598340,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017857,AGAP009194-RA,...,G,P,Q,NON_SYNONYMOUS_CODING,MODERATE,76.0,33.0,T,0.017857,"P56Q (3R:28,598,340 G>T)"
G26S,3R,28598505,0.009804,0.05,0.041667,0.000000,0.000000,0.013514,0.047619,0.000000,0.000000,AGAP009194-RA,...,C,G,S,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,T,0.050000,"G26S (3R:28,598,505 C>T)"
T21A,3R,28598520,0.715686,0.80,0.708333,0.807692,0.857143,0.729730,0.785714,0.889610,0.839286,AGAP009194-RA,...,T,T,A,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,C,0.889610,"T21A (3R:28,598,520 T>C)"
L20Q,3R,28598522,0.000000,0.00,0.000000,0.000000,0.000000,0.013514,0.000000,0.000000,0.000000,AGAP009194-RA,...,A,L,Q,NON_SYNONYMOUS_CODING,MODERATE,113.0,24.0,T,0.013514,"L20Q (3R:28,598,522 A>T)"
L11I,3R,28598550,0.009804,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,AGAP009194-RA,...,G,L,I,NON_SYNONYMOUS_CODING,MODERATE,5.0,5.0,T,0.009804,"L11I (3R:28,598,550 G>T)"
N3K,3R,28598572,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,AGAP009194-RA,...,G,N,K,NON_SYNONYMOUS_CODING,MODERATE,23.0,27.0,C,1.000000,"N3K (3R:28,598,572 G>C)"

In [ ]:
df_gst_freq_gambia.query("max_af > 0.05")

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
A185T,3R,28597864,0.225490,0.15,0.250000,0.038462,0.107143,0.216216,0.119048,0.045455,0.125000,AGAP009194-RA,...,C,A,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,T,0.250000,"A185T (3R:28,597,864 C>T)"
T154S,3R,28597956,0.852941,0.90,0.833333,0.961538,0.857143,0.891892,0.904762,0.980519,0.821429,AGAP009194-RA,...,G,T,S,NON_SYNONYMOUS_CODING,MODERATE,58.0,12.0,C,0.980519,"T154S (3R:28,597,956 G>C)"
S98A,3R,28598215,0.166667,0.10,0.208333,0.000000,0.214286,0.162162,0.142857,0.006494,0.089286,AGAP009194-RA,...,A,S,A,NON_SYNONYMOUS_CODING,MODERATE,99.0,16.0,C,0.214286,"S98A (3R:28,598,215 A>C)"
V91I,3R,28598236,0.039216,0.05,0.083333,0.038462,0.017857,0.054054,0.047619,0.006494,0.000000,AGAP009194-RA,...,C,V,I,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,T,0.083333,"V91I (3R:28,598,236 C>T)"
T21A,3R,28598520,0.715686,0.80,0.708333,0.807692,0.857143,0.729730,0.785714,0.889610,0.839286,AGAP009194-RA,...,T,T,A,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,C,0.889610,"T21A (3R:28,598,520 T>C)"
N3K,3R,28598572,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,AGAP009194-RA,...,G,N,K,NON_SYNONYMOUS_CODING,MODERATE,23.0,27.0,C,1.000000,"N3K (3R:28,598,572 G>C)"

In [ ]:
ag3.plot_frequencies_heatmap(
    df_gst_freq_gambia.query("max_af > 0.05")
)

In [ ]:
ag3.plot_frequencies_heatmap(
    df_gst_freq_gambia.query("max_af > 0.05")[["label"] + [f"frq_{c}" for c in arab_cohorts_admin2_year]],
    row_height=30,
    color_continuous_scale='Turbo'
)

#### **Rdl - gama-aminobutyric acid (GABA)**

In [ ]:
color_mapping_admin2 = {
    'Jarra East': '#8e8c84',
    'Lower Fuladu West': '#7f7f7f',
    'Upper Fuladu West': '#6b705c',
    'Niani': '#4a4e4d',
    'Niamina East': '#3b5c40',
    'Jimara': '#8e7d32',
    'Basse': '#a95b29',
    'Wuli East': '#b64d3b',
    'Tumana': '#8a4b39',
    'Niamina West': '#6f4e37',
    'Sandu': '#3e3a3a',
    'Jeshwang': '#a4c9e2',
    'Kombo Central': '#78aaff',
    'Lower Niumi': '#4d88ff',
    'Bakau': '#0077b6',
    'Illiasa': '#0096c7',
    'Foni Brefet': '#00b4d8'
}

In [ ]:
rdl_region = "2L:25,363,652-25,434,556"

In [ ]:
ag3.genome_features(region=rdl_region)

,contig,source,type,start,end,score,strand,phase,ID,Parent,Name,description
0,2L,VectorBase,chromosome,1,49364325,NaN,NaN,NaN,2L,NaN,NaN,NaN
1,2L,VectorBase,gene,25363652,25434556,NaN,+,NaN,AGAP006028,NaN,Rdl,GABA-gated chloride channel subunit [Source:VB...
2,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RA,AGAP006028,NaN,NaN
3,2L,VectorBase,exon,25363652,25363776,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E1,NaN
4,2L,VectorBase,CDS,25363652,25363776,NaN,+,0.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
5,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RB,AGAP006028,NaN,NaN
6,2L,VectorBase,exon,25363652,25363776,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E1,NaN
7,2L,VectorBase,CDS,25363652,25363776,NaN,+,0.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
8,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RC,AGAP006028,NaN,NaN
9,2L,VectorBase,exon,25363652,25363776,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E1,NaN
10,2L,VectorBase,CDS,25363652,25363776,NaN,+,0.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
11,2L,VectorBase,exon,25382776,25382873,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E2,NaN
12,2L,VectorBase,CDS,25382776,25382873,NaN,+,1.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
13,2L,VectorBase,exon,25382776,25382873,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E2,NaN
14,2L,VectorBase,CDS,25382776,25382873,NaN,+,1.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
15,2L,VectorBase,exon,25382776,25382873,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E2,NaN
16,2L,VectorBase,CDS,25382776,25382873,NaN,+,1.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
17,2L,VectorBase,exon,25387091,25387158,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E3,NaN
18,2L,VectorBase,CDS,25387091,25387158,NaN,+,2.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
19,2L,VectorBase,exon,25387091,25387158,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E3,NaN
20,2L,VectorBase,CDS,25387091,25387158,NaN,+,2.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
21,2L,VectorBase,exon,25391242,25391309,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RC-E3,NaN
22,2L,VectorBase,CDS,25391242,25391309,NaN,+,2.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
23,2L,VectorBase,exon,25398915,25399141,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E4,NaN
24,2L,VectorBase,CDS,25398915,25399141,NaN,+,0.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
25,2L,VectorBase,exon,25398915,25399141,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E4,NaN
26,2L,VectorBase,CDS,25398915,25399141,NaN,+,0.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
27,2L,VectorBase,exon,25398915,25399141,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E4,NaN
28,2L,VectorBase,CDS,25398915,25399141,NaN,+,0.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
29,2L,VectorBase,exon,25400694,25400776,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E5,NaN
30,2L,VectorBase,CDS,25400694,25400776,NaN,+,1.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
31,2L,VectorBase,exon,25400694,25400776,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E5,NaN
32,2L,VectorBase,CDS,25400694,25400776,NaN,+,1.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
33,2L,VectorBase,exon,25400694,25400776,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E5,NaN
34,2L,VectorBase,CDS,25400694,25400776,NaN,+,1.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
35,2L,VectorBase,exon,25413237,25413374,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E6,NaN
36,2L,VectorBase,CDS,25413237,25413374,NaN,+,2.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
37,2L,VectorBase,exon,25413237,25413374,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E6,NaN
38,2L,VectorBase,CDS,25413237,25413374,NaN,+,2.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
39,2L,VectorBase,exon,25418624,25418761,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RB-E6,NaN
40,2L,VectorBase,CDS,25418624,25418761,NaN,+,2.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
41,2L,VectorBase,exon,25429089,25429373,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E7,NaN
42,2L,VectorBase,CDS,25429089,25429373,NaN,+,2.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
43,2L,VectorBase,exon,25429089,25429373,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E7,NaN
44,2L,VectorBase,CDS,25429089,25429373,NaN,+,2.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
45,2L,VectorBase,exon,25429089,25429373,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E7,NaN
46,2L,VectorBase,CDS,25429089,25429373,NaN,+,2.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
47,2L,VectorBase,exon,25433162,25433640,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E8,NaN
48,2L,VectorBase,CDS,25433162,25433640,NaN,+,2.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
49,2L,VectorBase,exon,25433162,25433640,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E8,NaN
50,2L,VectorBase,CDS,25433162,25433640,NaN,+,2.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
51,2L,VectorBase,exon,25433162,25433640,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E8,NaN
52,2L,VectorBase,CDS,25433162,25433640,NaN,+,2.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN
53,2L,VectorBase,exon,25434392,25434556,NaN,+,NaN,NaN,AGAP006028-RA,AGAP006028-RA-E9,NaN
54,2L,VectorBase,CDS,25434392,25434556,NaN,+,0.0,AGAP006028-PA,AGAP006028-RA,NaN,NaN
55,2L,VectorBase,exon,25434392,25434556,NaN,+,NaN,NaN,AGAP006028-RB,AGAP006028-RA-E9,NaN
56,2L,VectorBase,CDS,25434392,25434556,NaN,+,0.0,AGAP006028-PB,AGAP006028-RB,NaN,NaN
57,2L,VectorBase,exon,25434392,25434556,NaN,+,NaN,NaN,AGAP006028-RC,AGAP006028-RA-E9,NaN
58,2L,VectorBase,CDS,25434392,25434556,NaN,+,0.0,AGAP006028-PC,AGAP006028-RC,NaN,NaN

In [ ]:
ag3.genome_features(region=rdl_region).query("type == 'mRNA'")

,contig,source,type,start,end,score,strand,phase,ID,Parent,Name,description
2,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RA,AGAP006028,NaN,NaN
5,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RB,AGAP006028,NaN,NaN
8,2L,VectorBase,mRNA,25363652,25434556,NaN,+,NaN,AGAP006028-RC,AGAP006028,NaN,NaN

In [ ]:
ag3.genome_features(region=rdl_region).query("type == 'gene'")

,contig,source,type,start,end,score,strand,phase,ID,Parent,Name,description
1,2L,VectorBase,gene,25363652,25434556,NaN,+,NaN,AGAP006028,NaN,Rdl,GABA-gated chloride channel subunit [Source:VB...

In [ ]:
df_rdl_freq_gambia = ag3.aa_allele_frequencies(
    transcript="AGAP006028-RA",
    sample_query=gambia_sample_query,
    cohorts="admin2_year",
)
df_rdl_freq_gambia

Load SNP genotypes:   0%|          | 0/38 [00:00<?, ?it/s]

Compute allele frequencies:   0%|          | 0/9 [00:00<?, ?it/s]

Compute SNP effects:   0%|          | 0/21565 [00:00<?, ?it/s]

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
S12G,2L,25363685,0.000000,0.05,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,A,S,G,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,G,0.050000,"S12G (2L:25,363,685 A>G)"
S12I,2L,25363686,0.009804,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,G,S,I,NON_SYNONYMOUS_CODING,MODERATE,142.0,23.0,T,0.009804,"S12I (2L:25,363,686 G>T)"
V17I,2L,25363700,0.000000,0.05,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,G,V,I,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,A,0.050000,"V17I (2L:25,363,700 G>A)"
I19V,2L,25363706,0.009804,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,A,I,V,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,G,0.009804,"I19V (2L:25,363,706 A>G)"
T31I,2L,25363743,0.000000,0.00,0.0,0.0,0.017857,0.027027,0.00000,0.0,0.0,AGAP006028-RA,...,C,T,I,NON_SYNONYMOUS_CODING,MODERATE,89.0,23.0,T,0.027027,"T31I (2L:25,363,743 C>T)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C525Y,2L,25434462,0.000000,0.00,0.0,0.0,0.000000,0.000000,0.02381,0.0,0.0,AGAP006028-RA,...,G,C,Y,NON_SYNONYMOUS_CODING,MODERATE,194.0,29.0,A,0.023810,"C525Y (2L:25,434,462 G>A)"
M532R,2L,25434483,0.000000,0.00,0.0,0.0,0.017857,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,T,M,R,NON_SYNONYMOUS_CODING,MODERATE,91.0,28.0,G,0.017857,"M532R (2L:25,434,483 T>G)"
S541G,2L,25434509,0.009804,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,A,S,G,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,G,0.009804,"S541G (2L:25,434,509 A>G)"
A545D,2L,25434522,0.000000,0.00,0.0,0.0,0.017857,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,C,A,D,NON_SYNONYMOUS_CODING,MODERATE,126.0,30.0,A,0.017857,"A545D (2L:25,434,522 C>A)"
A545G,2L,25434522,0.009804,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.0,AGAP006028-RA,...,C,A,G,NON_SYNONYMOUS_CODING,MODERATE,60.0,9.0,G,0.009804,"A545G (2L:25,434,522 C>G)"

In [ ]:
df_rdl_freq_gambia.query("max_af > 0.03")

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
S12G,2L,25363685,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,S,G,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,G,0.050000,"S12G (2L:25,363,685 A>G)"
V17I,2L,25363700,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,G,V,I,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,A,0.050000,"V17I (2L:25,363,700 G>A)"
E79D,2L,25387104,0.049020,0.00,0.083333,0.461538,0.071429,0.054054,0.02381,0.493506,0.392857,AGAP006028-RA,...,A,E,D,NON_SYNONYMOUS_CODING,MODERATE,160.0,7.0,C,0.493506,"E79D (2L:25,387,104 A>C)"
V80E,2L,25387106,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,T,V,E,NON_SYNONYMOUS_CODING,MODERATE,121.0,31.0,A,0.050000,"V80E (2L:25,387,106 T>A)"
V95D,2L,25387151,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,T,V,D,NON_SYNONYMOUS_CODING,MODERATE,152.0,28.0,A,0.050000,"V95D (2L:25,387,151 T>A)"
M97V,2L,25387156,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,M,V,NON_SYNONYMOUS_CODING,MODERATE,21.0,23.0,G,0.050000,"M97V (2L:25,387,156 A>G)"
F105L,2L,25398938,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,C,F,L,NON_SYNONYMOUS_CODING,MODERATE,22.0,22.0,G,0.050000,"F105L (2L:25,398,938 C>G)"
Q107H,2L,25398944,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,Q,H,NON_SYNONYMOUS_CODING,MODERATE,46.0,27.0,C,0.050000,"Q107H (2L:25,398,944 A>C)"
G128V,2L,25399006,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,G,G,V,NON_SYNONYMOUS_CODING,MODERATE,109.0,19.0,T,0.050000,"G128V (2L:25,399,006 G>T)"
I162L,2L,25399107,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,I,L,NON_SYNONYMOUS_CODING,MODERATE,5.0,5.0,T,0.050000,"I162L (2L:25,399,107 A>T)"
S200G,2L,25400773,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,S,G,NON_SYNONYMOUS_CODING,MODERATE,56.0,19.0,G,0.050000,"S200G (2L:25,400,773 A>G)"
G220*,2L,25413293,0.009804,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,G,G,*,STOP_GAINED,HIGH,NaN,NaN,T,0.050000,"G220* (2L:25,413,293 G>T)"
P292L,2L,25429224,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.006494,0.000000,AGAP006028-RA,...,C,P,L,NON_SYNONYMOUS_CODING,MODERATE,98.0,24.0,T,0.050000,"P292L (2L:25,429,224 C>T)"
A296S,2L,25429235,0.068627,0.00,0.125000,0.615385,0.107143,0.094595,0.02381,0.623377,0.500000,AGAP006028-RA,...,G,A,S,NON_SYNONYMOUS_CODING,MODERATE,99.0,16.0,T,0.623377,"A296S (2L:25,429,235 G>T)"
T307A,2L,25429268,0.000000,0.00,0.041667,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,A,T,A,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,G,0.041667,"T307A (2L:25,429,268 A>G)"
L316*,2L,25429296,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,T,L,*,STOP_GAINED,HIGH,NaN,NaN,A,0.050000,"L316* (2L:25,429,296 T>A)"
D326N,2L,25429325,0.000000,0.00,0.041667,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,G,D,N,NON_SYNONYMOUS_CODING,MODERATE,42.0,14.0,A,0.041667,"D326N (2L:25,429,325 G>A)"
C332F,2L,25429344,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,G,C,F,NON_SYNONYMOUS_CODING,MODERATE,205.0,25.0,T,0.050000,"C332F (2L:25,429,344 G>T)"
T345S,2L,25433170,0.019608,0.00,0.041667,0.153846,0.035714,0.040541,0.00000,0.123377,0.125000,AGAP006028-RA,...,A,T,S,NON_SYNONYMOUS_CODING,MODERATE,58.0,12.0,T,0.153846,"T345S (2L:25,433,170 A>T)"
A375T,2L,25433260,0.019608,0.00,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.035714,AGAP006028-RA,...,G,A,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,A,0.035714,"A375T (2L:25,433,260 G>A)"
V439G,2L,25433453,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP006028-RA,...,T,V,G,NON_SYNONYMOUS_CODING,MODERATE,109.0,19.0,G,0.050000,"V439G (2L:25,433,453 T>G)"

In [ ]:
ag3.plot_frequencies_heatmap(
    df_rdl_freq_gambia.query("max_af > 0.05")
)

In [ ]:
ag3.plot_frequencies_heatmap(
    df_rdl_freq_gambia.query("max_af > 0.05")[["label"] + [f"frq_{c}" for c in arab_cohorts_admin2_year]],
    row_height=40,
    color_continuous_scale='Turbo'
)

In [ ]:
ag3.plot_cnv_hmm_heatmap(
    region='2L:25,363,652-25,500,000',
    sample_query='taxon == "arabiensis"',
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
    row_height=2
);

In [ ]:
ag3.plot_diplotype_clustering_advanced(
    region=rdl_region,
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
    cnv_region=rdl_region,
    cnv_max_coverage_variance=0.8,
    snp_transcript="AGAP006028-RA",
    color="admin2_name",
    color_discrete_map=color_mapping_admin2
    )

Load genotypes for distance calculation:   0%|          | 0/17 [00:00<?, ?it/s]

Load genotypes for heterozygosity calculation:   0%|          | 0/17 [00:00<?, ?it/s]

Load CNV HMM data:   0%|          | 0/34 [00:00<?, ?it/s]

Compute modal gene copy number:   0%|          | 0/1 [00:00<?, ?it/s]

Load SNP genotypes:   0%|          | 0/17 [00:00<?, ?it/s]

Compute SNP effects:   0%|          | 0/212715 [00:00<?, ?it/s]

#### **Organophosphate resistance markers (Ace1)**

In [ ]:
ace1_aa_freqs_df = ag3.aa_allele_frequencies(
    transcript="AGAP001356-RA",
    cohorts="admin2_year",
    sample_query=gambia_sample_query
)

ace1_aa_freqs_df

Load SNP genotypes:   0%|          | 0/38 [00:00<?, ?it/s]

Compute allele frequencies:   0%|          | 0/9 [00:00<?, ?it/s]

Compute SNP effects:   0%|          | 0/3931 [00:00<?, ?it/s]

,,,frq_GM-M_Lower-Fuladu-West_arab_2019,frq_GM-M_Niamina-East_arab_2019,frq_GM-M_Upper-Fuladu-West_arab_2019,frq_GM-N_Lower-Niumi_arab_2019,frq_GM-U_Basse_arab_2019,frq_GM-U_Jimara_arab_2019,frq_GM-U_Tumana_arab_2019,frq_GM-W_Jeshwang_arab_2019,frq_GM-W_Kombo-Central_arab_2019,transcript,...,ref_allele,ref_aa,alt_aa,effect,impact,grantham_score,sneath_score,alt_allele,max_af,label
aa_change,contig,position,,,,,,,,,,,,,,,,,,,,,
G9C,2R,3489237,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.017857,AGAP001356-RA,...,G,G,C,NON_SYNONYMOUS_CODING,MODERATE,159.0,21.0,T,0.017857,"G9C (2R:3,489,237 G>T)"
R10S,2R,3489242,0.000000,0.0,0.000000,0.0,0.000000,0.013514,0.00000,0.000000,0.000000,AGAP001356-RA,...,A,R,S,NON_SYNONYMOUS_CODING,MODERATE,110.0,37.0,T,0.013514,"R10S (2R:3,489,242 A>T)"
R12W,2R,3489246,0.000000,0.0,0.000000,0.0,0.000000,0.013514,0.00000,0.000000,0.000000,AGAP001356-RA,...,C,R,W,NON_SYNONYMOUS_CODING,MODERATE,101.0,36.0,T,0.013514,"R12W (2R:3,489,246 C>T)"
R16L,2R,3489259,0.000000,0.0,0.000000,0.0,0.017857,0.000000,0.00000,0.000000,0.000000,AGAP001356-RA,...,G,R,L,NON_SYNONYMOUS_CODING,MODERATE,102.0,34.0,T,0.017857,"R16L (2R:3,489,259 G>T)"
M17I,2R,3489263,0.009804,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP001356-RA,...,G,M,I,NON_SYNONYMOUS_CODING,MODERATE,10.0,20.0,T,0.009804,"M17I (2R:3,489,263 G>T)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V726M,2R,3493750,0.000000,0.0,0.000000,0.0,0.017857,0.000000,0.02381,0.000000,0.000000,AGAP001356-RA,...,G,V,M,NON_SYNONYMOUS_CODING,MODERATE,21.0,23.0,A,0.023810,"V726M (2R:3,493,750 G>A)"
A731T,2R,3493765,0.000000,0.0,0.041667,0.0,0.017857,0.013514,0.00000,0.012987,0.000000,AGAP001356-RA,...,G,A,T,NON_SYNONYMOUS_CODING,MODERATE,58.0,20.0,A,0.041667,"A731T (2R:3,493,765 G>A)"
A731G,2R,3493766,0.009804,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,AGAP001356-RA,...,C,A,G,NON_SYNONYMOUS_CODING,MODERATE,60.0,9.0,G,0.009804,"A731G (2R:3,493,766 C>G)"
V733I,2R,3493771,0.000000,0.0,0.000000,0.0,0.000000,0.013514,0.00000,0.000000,0.000000,AGAP001356-RA,...,G,V,I,NON_SYNONYMOUS_CODING,MODERATE,29.0,9.0,A,0.013514,"V733I (2R:3,493,771 G>A)"
Q737K,2R,3493783,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.017857,AGAP001356-RA,...,C,Q,K,NON_SYNONYMOUS_CODING,MODERATE,61.0,21.0,A,0.017857,"Q737K (2R:3,493,783 C>A)"

In [ ]:
ace1_aa_filt_df = ace1_aa_freqs_df.query("max_af >= 0.05")
ace1_aa_filt_df

In [ ]:
ag3.plot_frequencies_heatmap(ace1_aa_filt_df, height=600, width=1000)

In [ ]:
ag3.plot_frequencies_heatmap(
    ace1_aa_freqs_df.query("max_af > 0.05")[["label"] + [f"frq_{c}" for c in arab_cohorts_admin2_year]],
    color_continuous_scale='Turbo',
    height=500,
    width=800
)

In [ ]:
ag3.plot_cnv_hmm_heatmap(
    region='2R:3,300,000-4,000,000',
    sample_query='taxon == "arabiensis"',
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
    row_height=2
);

In [ ]:
ag3.sample_sets(release=["3.9"])

In [ ]:
ag3.plot_cnv_hmm_heatmap(
    region='2R:3,300,000-4,000,000',
    sample_query='taxon == "arabiensis"',
    sample_sets='1191-VO-MULTI-OLOUGHLIN-VMF00140',
    row_height=2
);

In [ ]:
ace1_cnv_freqs_df = ag3.gene_cnv_frequencies(
    region="2R:3,483,099-3,497,400",
    cohorts="admin2_year",
    sample_query="country == 'Gambia, The' and taxon == 'arabiensis'",
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
)
ace1_cnv_freqs_df

In [ ]:
ace1_cnv_freqs_df = ag3.gene_cnv_frequencies(
    region="2R:3,300,000-4,000,000",
    cohorts="admin2_year",
    sample_query="country == 'Gambia, The' and taxon == 'arabiensis'",
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
)
ace1_cnv_freqs_df

**Diplotype clustering in target site markers**

In [ ]:
ag3.genome_features(region="AGAP004707-RD").query("type == 'gene'")

In [ ]:
vgsc_region = "2L: 2,358,158-2,431,617"
rdl_region = "2L:25,363,652-25,434,556"
gst_region = "3R:28,597,000-28,600,000"
ace1_region = "2R:3,300,000-4,000,000"
ace_region = "2R:3,483,099-3,497,400"

sample_sets = ["AG1000G-GM-A", "AG1000G-GM-B", "AG1000G-GM-C", "1272-VO-GM-OPONDO-VMF00160"]

In [ ]:
ag3.plot_diplotype_clustering_advanced(
    region=[rdl_region, vgsc_region, gst_region, ace1_region, ace_region],
    sample_sets='1272-VO-GM-OPONDO-VMF00160',
    cnv_region=[rdl_region, vgsc_region, gst_region, ace1_region, ace_region],
    cnv_max_coverage_variance=0.8,
    #snp_transcript="AGAP006028-RA",
    color="admin2_name",
    color_discrete_map=color_mapping_admin2
    )